

version: '3.9'
services:
  sv_web:
    container_name: webserver
    build:
      context: ./
      dockerfile: dockerfile-php
    depends_on:
      - sv_db
    restart: always
    volumes:
           - ./html/:/var/www/html/
    ports:
        - '80:80'
    networks:
       vpcbr:
         ipv4_address: 10.1.1.11

  sv_web:
    container_name: goweb
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - sv_db
    restart: always
    volumes:
           - ./www/:/var/www/html/
    ports:
        - '9014:9014'
    networks:
       vpcbr:
         ipv4_address: 10.1.1.11

  sv_db:
    image: mysql:5.6
    volumes:
    - ./mysql-backup/:/docker-entrypoint-initdb.d/
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: 0014_Lab_Exam
      MYSQL_USER: 645162010014
      MYSQL_PASSWORD: 645162010014
    ports:
      - '3306:3306'
    networks:
       vpcbr:
         ipv4_address: 10.1.1.22

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.1

